name: Setup MicroPython Port Builder Composite Action
description: Port builder actions for MicroPython steps
author: FoBE Studio
branding:
  icon: chevron-right
  color: purple

inputs:
  repo_remote:
    description: The MicroPython repository remote ('origin', 'upstream')
    default: origin
    required: false
  repo_ref:
    description: The MicroPython repository reference (branch, tag, commit)
    default: main
    required: false
  port:
    description: The MicroPython platform to build (esp32, nrf)
    required: true
  board:
    description: The MicroPython board to build
    default: ""
    required: false

runs:
  using: composite
  steps:
    - id: build_micropython
      run: |
        sudo rm -rf $GITHUB_WORKSPACE/bin
        sudo mkdir -p $GITHUB_WORKSPACE/bin
        docker run --rm \
          --env GITHUB_ACTIONS \
          --env REPO_REMOTE \
          --env REPO_REF \
          --env BOARD \
          -v $GITHUB_WORKSPACE/bin:/workspace/bin \
          ghcr.io/fobe-projects/action-micropython-builder:main-${{ inputs.port }}
      shell: bash
      env:
        REPO_REMOTE: ${{ inputs.repo_remote }}
        REPO_REF: ${{ inputs.repo_ref }}
        BOARD: ${{ inputs.board }}